# Generated by Django 2.2.7 on 2019-11-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('short_url', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='Короткий URL')),
                ('original_url', models.URLField(unique=True, verbose_name='Оригинальный URL')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('number_of_visits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'url',
                'ordering': ['-creation_date'],
            },
        ),
    ]
