# Generated by Django 2.2.7 on 2019-11-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191106_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(verbose_name='Оригинальный URL'),
        ),
    ]
